// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Drivetrain.h"
#include "../RobotMap.h"

Drivetrain::Drivetrain() : Subsystem("Drivetrain") {
    frontLeft = RobotMap::drivetrainFrontLeft;
    frontRight = RobotMap::drivetrainFrontRight;
    rearRight = RobotMap::drivetrainRearRight;
    rearLeft = RobotMap::drivetrainRearLeft;
    robotDrive = RobotMap::drivetrainRobotDrive;
    strafe = RobotMap::drivetrainStrafe;
<<<<<<< HEAD

    //navX = RobotMap::drivetrainNavX; // added to Gyroscope
=======
    orient = -1;
    navX = RobotMap::drivetrainNavX;

>>>>>>> 6f9831f71a467890abc5d61bd92c8aea2e78d370
}

void Drivetrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
}

void Drivetrain::DriveWithJoystick(std::shared_ptr<Joystick> joy){
	robotDrive->ArcadeDrive(joy->GetY()*orient, joy->GetX());
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

